
import com.nse.listingcompliance.lcdebtannouncementservice.drools.classes.AutoEmail;

rule "Auto email Category 2 and Subject Type 3"
    when
        autoEmail : AutoEmail(categoryId == 2 && subjectTypeId == 3)
    then
        autoEmail.setAutoEmailStatus(true);
    end


rule "Auto email Category 2 and Subject Type 4"
    when
        autoEmail : AutoEmail(categoryId == 2 && subjectTypeId == 4)
    then
        autoEmail.setAutoEmailStatus(true);
    end


rule "Auto email Category 2 and Subject Type 5"
    when
        autoEmail : AutoEmail(categoryId == 2 && subjectTypeId == 5)
    then
        autoEmail.setAutoEmailStatus(false);
    end

rule "Auto email Category 2 and Subject Type 6"
    when
        autoEmail : AutoEmail(categoryId == 2 && subjectTypeId == 6)
    then
        autoEmail.setAutoEmailStatus(false);
    end

rule "Auto email Category 2 and Subject Type 7"
    when
        autoEmail : AutoEmail(categoryId == 2 && subjectTypeId == 7)
    then
        autoEmail.setAutoEmailStatus(false);
    end

rule "Auto email Category 4 and Subject Type 13"
    when
        autoEmail : AutoEmail(categoryId == 4 && subjectTypeId == 13)
    then
        autoEmail.setAutoEmailStatus(true);
    end

rule "Auto email Category 4 and Subject Type 14"
    when
        autoEmail : AutoEmail(categoryId == 4 && subjectTypeId == 14)
    then
        autoEmail.setAutoEmailStatus(false);
    end

rule "Auto email Category 4 and Subject Type 15"
    when
        autoEmail : AutoEmail(categoryId == 4 && subjectTypeId == 15)
    then
        autoEmail.setAutoEmailStatus(true);
    end

rule "Auto email Category  4 and Subject Type 16"
    when
        autoEmail : AutoEmail(categoryId == 4 && subjectTypeId == 16)
    then
        autoEmail.setAutoEmailStatus(false);
    end

rule "Auto email Category 4 and Subject Type 17"
    when
        autoEmail : AutoEmail(categoryId == 4 && subjectTypeId == 17)
    then
        autoEmail.setAutoEmailStatus(false);
    end

rule "Auto email Category 4 and Subject Type 18"
    when
        autoEmail : AutoEmail(categoryId == 4 && subjectTypeId == 18)
    then
        autoEmail.setAutoEmailStatus(false);
    end

rule "Auto email Category 3 and Subject Type 8"
    when
        autoEmail : AutoEmail(categoryId == 3 && subjectTypeId == 8)
    then
        autoEmail.setAutoEmailStatus(true);
    end

rule "Auto email Category 3 and Subject Type 9"
    when
        autoEmail : AutoEmail(categoryId == 3 && subjectTypeId == 9)
    then
        autoEmail.setAutoEmailStatus(true);
    end

rule "Auto email Category 3 and Subject Type 10"
    when
        autoEmail : AutoEmail(categoryId == 3 && subjectTypeId == 10)
    then
        autoEmail.setAutoEmailStatus(false);
    end

rule "Auto email Category 3 and Subject Type 11"
    when
        autoEmail : AutoEmail(categoryId == 3 && subjectTypeId == 11)
    then
        autoEmail.setAutoEmailStatus(true);
    end

rule "Auto email Category 3 and Subject Type 12"
    when
        autoEmail : AutoEmail(categoryId == 3 && subjectTypeId == 12)
    then
        autoEmail.setAutoEmailStatus(false);
    end

rule "Auto email Category 5 and Subject Type 19"
    when
        autoEmail : AutoEmail(categoryId == 5 && subjectTypeId == 19)
    then
        autoEmail.setAutoEmailStatus(false);
    end

rule "Auto email Category 5 and Subject Type 20"
    when
        autoEmail : AutoEmail(categoryId == 5 && subjectTypeId == 20)
    then
        autoEmail.setAutoEmailStatus(false);
    end

rule "Auto email Category 5 and Subject Type 21"
    when
        autoEmail : AutoEmail(categoryId == 5 && subjectTypeId == 21)
    then
        autoEmail.setAutoEmailStatus(false);
    end

rule "Auto email Category 1 and Subject Type 2"
    when
        autoEmail : AutoEmail(categoryId == 1 && subjectTypeId == 2)
    then
        autoEmail.setAutoEmailStatus(true);
    end

rule "Auto email Category 1 and Subject Type 1"
    when
        autoEmail : AutoEmail(categoryId == 1 && subjectTypeId == 1)
    then
        autoEmail.setAutoEmailStatus(false);
    end

rule "Auto email Category 7 and Subject Type 31"
    when
        autoEmail : AutoEmail(categoryId == 7 && subjectTypeId == 31)
    then
        autoEmail.setAutoEmailStatus(false);
    end

rule "Auto email Category 7 and Subject Type 32"
    when
        autoEmail : AutoEmail(categoryId == 7 && subjectTypeId == 32)
    then
        autoEmail.setAutoEmailStatus(false);
    end

rule "Auto email Category 7 and Subject Type 33"
    when
        autoEmail : AutoEmail(categoryId == 7 && subjectTypeId == 33)
    then
        autoEmail.setAutoEmailStatus(false);
    end

rule "Auto email Category 7 and Subject Type 34"
    when
        autoEmail : AutoEmail(categoryId == 7 && subjectTypeId == 34)
    then
        autoEmail.setAutoEmailStatus(false);
    end

rule "Auto email Category 6 and Subject Type 28"
    when
        autoEmail : AutoEmail(categoryId == 6 && subjectTypeId == 28)
    then
        autoEmail.setAutoEmailStatus(true);
    end

rule "Auto email Category 6 and Subject Type 22"
    when
        autoEmail : AutoEmail(categoryId == 6 && subjectTypeId == 22)
    then
        autoEmail.setAutoEmailStatus(true);
    end

rule "Auto email Category 6 and Subject Type 23"
    when
        autoEmail : AutoEmail(categoryId == 6 && subjectTypeId == 23)
    then
        autoEmail.setAutoEmailStatus(false);
    end

rule "Auto email Category 6 and Subject Type 24"
    when
        autoEmail : AutoEmail(categoryId == 6 && subjectTypeId == 24)
    then
        autoEmail.setAutoEmailStatus(false);
    end

rule "Auto email Category 6 and Subject Type 25"
    when
        autoEmail : AutoEmail(categoryId == 6 && subjectTypeId == 25)
    then
        autoEmail.setAutoEmailStatus(false);
    end

rule "Auto email Category 6 and Subject Type 26"
    when
        autoEmail : AutoEmail(categoryId == 6 && subjectTypeId == 26)
    then
        autoEmail.setAutoEmailStatus(false);
    end

rule "Auto email Category 6 and Subject Type 29"
    when
        autoEmail : AutoEmail(categoryId == 6 && subjectTypeId == 29)
    then
        autoEmail.setAutoEmailStatus(false);
    end

rule "Auto email Category 6 and Subject Type 27"
    when
        autoEmail : AutoEmail(categoryId == 6 && subjectTypeId == 27)
    then
        autoEmail.setAutoEmailStatus(false);
    end

rule "Auto email Category 6 and Subject Type 30"
    when
        autoEmail : AutoEmail(categoryId == 6 && subjectTypeId == 30)
    then
        autoEmail.setAutoEmailStatus(false);
    end